### PR TITLE
New data from 210317

### PR DESCRIPTION
**Pull request by vng**
Signed-off-by: vng <viktor.govako@gmail.com>

### CODE REVIEW

**Comment by rtsisyk** [comment]
I think we can wait one week and update data in April.

**Comment by vng** [comment]
No problem here. But this is the first data, generated with fast_math, so feel free to test ..

**Review by biodranik — APPROVED** [review]
LGTM

**Comment by biodranik** [comment]
The earlier we start testing the better.

**Comment by biodranik** [comment]
@vng @rtsisyk please deploy it

**Pull request merged**
